# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mapreduce.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mapreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\tmapreduce\x1a\x1bgoogle/protobuf/empty.proto\"P\n\nMapRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\x05\x12\x13\n\x0bnum_workers\x18\x04 \x01(\x05\"6\n\rReduceRequest\x12\x12\n\nworker_ids\x18\x01 \x03(\x05\x12\x11\n\tworker_id\x18\x02 \x01(\x05\x32\x81\x01\n\tMapReduce\x12\x36\n\x03Map\x12\x15.mapreduce.MapRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n\x06Reduce\x12\x18.mapreduce.ReduceRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=59
  _globals['_MAPREQUEST']._serialized_end=139
  _globals['_REDUCEREQUEST']._serialized_start=141
  _globals['_REDUCEREQUEST']._serialized_end=195
  _globals['_MAPREDUCE']._serialized_start=198
  _globals['_MAPREDUCE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
