syntax = "proto3";
package mapreduce;
import "google/protobuf/empty.proto";

service MapReduce {
    rpc Map(MapRequest) returns (google.protobuf.Empty) {}
    rpc FinalizeMap(google.protobuf.Empty) returns (google.protobuf.Empty) {}
    rpc Reduce(ReduceRequest) returns (google.protobuf.Empty) {}
    rpc EndPhase(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message MapRequest {
    string    key         = 1;  
    string    value       = 2;   
    int32     worker_id   = 3;
    int32     num_workers = 4;
}

message ReduceRequest {
    repeated int32 worker_ids = 1;  
    int32 worker_id = 2; 
}
