syntax = "proto3";
package mapreduce;
import "google/protobuf/empty.proto";

service MapReduce {
    rpc Map(MapRequest) returns (google.protobuf.Empty) {}
    rpc FinalizeMap(google.protobuf.Empty) returns (google.protobuf.Empty) {}
    rpc Reduce(ReduceRequest) returns (google.protobuf.Empty) {}
    rpc EndPhase(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message MapRequest {
    int32     map_task_id            = 1;
    string    input_path             = 2;
    int64     byte_start             = 3;
    int64     byte_end               = 4;
    int32     assigned_worker_id     = 5;
    int32     num_reduce_partitions  = 6;
}

message ReduceRequest {
    repeated int32 mapper_worker_ids = 1;
    int32 assigned_worker_id = 2;
    int32 reduce_partition_id = 3;
}
